//
//  SortModels.swift
//  GitHubRepoSearch
//
//  Created by Bojan Gaspar on 01/05/2020.
//  Copyright (c) 2020 UltraDev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct SortSection {
    let title: String
    var items: [SortItem]
}

struct SortItem {
    let title: String
    let type: SortType
    var value: Bool
}

enum SortType: String {
    case bestMatch, stars, forks, updated, asc, desc
}
